#File: config.yml
VERBOSE: True

MODEL:
  SESSION: 'uieb'
  INPUT: 'raw'
  TARGET: 'ref'
  INPUT_CHANNELS: 3
  NAME: 'model'  
  DATASET_NAME: 'UIEB'  # NEW: Specify the dataset name
  BASE_CHANNELS: 64
  EDGE_MODULE: True
  ATTENTION_MODULE: True
  EDGE_VK: True
  EDGE_HK: True
  EDGE_CK: True
  INIT_WEIGHTS: True
# Optimization arguments.
OPTIM:
  BATCH_SIZE: 12
  NUM_EPOCHS: 300
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  SEED: 3407
  WANDB: True

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  WEIGHT: ''
  PS_W: 256
  PS_H: 256
  TRAIN_DIR: './image_dirs/UIEB/train' # path to training data
  VAL_DIR: './image_dirs/UIEB/val'     # path to validation data
  SAVE_DIR: './checkpoints'  # Ensure this path is valid and not empty
  ORI: False
  LOG_FILE: 'log.txt'  # Ensure this path is not empty
  CLIP_GRAD: 0.0         # NEW: Gradient clipping norm
  MIXED_PRECISION: "no"  # 'no' (default), 'fp16', or 'bf16'.")

TESTING:
  INPUT: 'raw'
  TARGET: 'ref'
  VAL_DIR: ''     # path to testing data
  WEIGHT: ''
  SAVE_IMAGES: True
  RESULT_DIR: 'results'
  LOG_FILE: 't01.txt'

LOG:
  LOG_DIR: './log'  # Ensure this path is valid and not empty

LOSSES:
  USE_PSNR: True
  PSNR_SCALE: 1.0
  USE_SSIM: True
  SSIM_SCALE: 0.9
  USE_LPIPS: True
  LPIPS_SCALE: 0.7
  USE_EDGE: True
  EDGE_SCALE: 0.05
  USE_FREQ: False
  FREQ_SCALE: 0.00
